version: '3.7'

services: 
  mem:
    image: memcached:alpine
    container_name: mem
    ports:
    - "11211:11211"
    user: "1000:1000"

  prod:
    container_name: prod
    image: openjdk:8-jre-alpine3.9
    volumes:
    #  - /home/Admin/docker/m2:/root/.m2/repository
     - jenkins_home:${JENKINS_HOME}
    working_dir: ${WORKSPACE}/app
    command: ["java", "-jar", "target/embedash-1.1-SNAPSHOT.jar", 
    "--spring.config.location=./application.properties"]
    depends_on: 
      - mem
    user: "1000:1000"

  static:
    container_name: static
    image: nginx:1.18-alpine
    volumes:
     - jenkins_home:${JENKINS_HOME} 
    # - ./app/target/classes:/target
     - st:/usr/share/nginx/html
    working_dir: ${WORKSPACE}/app/target
    command: >
      sh -c "ls &&
          rm -f /usr/share/nginx/html/index.html || : &&
          rm -rf /usr/share/nginx/html/static || : &&
          cp -vr /app/target/static /usr/share/nginx/html/static &&
          cp -vf nginx.conf /etc/nginx/nginx.conf &&
          rm -rf /app/target/static"

  ng:
    container_name: ng
    image: nginx:1.18-alpine
    volumes:
      - jenkins_home:${JENKINS_HOME}
      - st:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "8080:8080"
    working_dir: ${WORKSPACE}
    command: [./my-wait.sh, prod, '9191', nginx-debug, '-g', 'daemon off;']
    depends_on: 
      - prod
    user: "1000:1000"

  e2e:
    container_name: e2e
    build:
      dockerfile: e2e.Dockerfile
      context: .
    image: e2e
    volumes:
     - jenkins_home:${JENKINS_HOME}
    working_dir: ${WORKSPACE}
    command: [./my-wait.sh, ng, '8080', ./e2e.sh]
    depends_on:
     - ng
    user: "1000:1000"

volumes:
  st:
  jenkins_home:
    external: true

networks:
  default:
    external:
      name: nt


