version: '3.7'

services: 
  mem:
    image: memcached:alpine
    container_name: mem
    ports:
    - "11211:11211"
    user: "1000:1000"

  prod:
    container_name: prod
    image: openjdk:8-jre-alpine3.9
    volumes:
      - /app:/app
    ports:
     - "9191:9191"
    working_dir: /app
    command: ["java", "-jar", "./embedash-1.1-SNAPSHOT.jar", 
    "--spring.config.location=./application.properties"]
    depends_on: 
      - mem

  ng:
    container_name: ng
    image: nginx:1.18-alpine
    volumes:
      - static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./my-wait.sh:/my-wait.sh
    ports:
     - "80:80"
    command: [./my-wait.sh, prod, '9191', nginx-debug, '-g', 'daemon off;']
    depends_on: 
      - prod

